doctrine_mongodb:
  connections:
    default:
      server: "%env(resolve:MONGODB_URL)%"
      options: {}
  default_database: events
  document_managers:
    default:
      auto_mapping: true
      mappings:
        App:
          is_bundle: false
          dir: '%kernel.project_dir%/src/Entity/ODM'
          prefix: 'App\Entity\ODM'
          alias: App
