version: '3'

services:
  database:
    image: postgres:latest
    ports:
      - "5435:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: app
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres

  php:
    build:
      context: ./php
    ports:
      - '9000:9000'
      - '3000:3000'
    volumes:
      - ./app:/var/www/symfony_docker
    depends_on:
      - database

  redis:
    image: redis

  consume:
    restart: on-failure #restart when vendor isn't ready or crash
    build:
      context: .
      dockerfile: consume/Dockerfile
    volumes:
      - ./app:/var/www/symfony_docker
    depends_on:
      - database
      - php
      - redis
      - nginx

  nginx:
    image: nginx:stable-alpine
    ports:
      - '8000:80'
    volumes:
      - ./app:/var/www/symfony_docker
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - database

volumes:
  db-data:
