export const LOAD_CLASSIFIERS = "LOAD_CLASSIFIERS";
export const CREATE_CLASSIFIER = "CREATE_CLASSIFIER";
export const UPDATE_CLASSIFIER = "UPDATE_CLASSIFIER";
export const DELETE_CLASSIFIER = "DELETE_CLASSIFIER";

export const LOAD_CLASSIFIER_DATA = "LOAD_CLASSIFIER_DATA";
export const CREATE_CLASSIFIER_DATA = "CREATE_CLASSIFIER_DATA";
export const UPDATE_CLASSIFIER_DATA = "UPDATE_CLASSIFIER_DATA";
export const DELETE_CLASSIFIER_DATA = "DELETE_CLASSIFIER_DATA";
